# Pandas Operations

In [2]:
import pandas as pd
df = pd.DataFrame([[1,2,3],[3,4,5],[5,6,7]], columns=['A','B','C'], index=['x','y','z'])

In [3]:
print(df)

   A  B  C
x  1  2  3
y  3  4  5
z  5  6  7

In [4]:
df.tail(2)

   A  B  C
y  3  4  5
z  5  6  7

In [5]:
df.index.tolist()

['x', 'y', 'z']

In [6]:
df.info()

<class 'pandas.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 99.0 bytes

In [7]:
print(df)

   A  B  C
x  1  2  3
y  3  4  5
z  5  6  7

In [8]:
df = pd.DataFrame([[1,2,0],[3,4,5],[5,0,7]], columns=['D','E','F'], index=['x','y','z'])
print(df)

   D  E  F
x  1  2  0
y  3  4  5
z  5  0  7

In [9]:
df.info()

<class 'pandas.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   D       3 non-null      int64
 1   E       3 non-null      int64
 2   F       3 non-null      int64
dtypes: int64(3)
memory usage: 99.0 bytes

In [10]:
import numpy as np
df = pd.DataFrame([[1,2,np.nan],[3,np.nan,5],[5,6,7]], columns=['A','B','C'], index=['x','y','z'])
print(df)

   A    B    C
x  1  2.0  NaN
y  3  NaN  5.0
z  5  6.0  7.0

In [11]:
df.info()

<class 'pandas.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       2 non-null      float64
 2   C       2 non-null      float64
dtypes: float64(2), int64(1)
memory usage: 99.0 bytes

In [12]:
# describe() gives us the count, mean, std, min, 25%, 50%, 75% and max values for each column in the dataframe
df.describe()

         A         B         C
count  3.0  2.000000  2.000000
mean   3.0  4.000000  6.000000
std    2.0  2.828427  1.414214
min    1.0  2.000000  5.000000
25%    2.0  3.000000  5.500000
50%    3.0  4.000000  6.000000
75%    4.0  5.000000  6.500000
max    5.0  6.000000  7.000000

In [13]:
# number of unique values in each column
df.nunique()

A    3
B    2
C    2
dtype: int64

In [14]:
print(df)

   A    B    C
x  1  2.0  NaN
y  3  NaN  5.0
z  5  6.0  7.0

In [15]:
# unique values in column A
df['A'].unique()

array([1, 3, 5])

In [16]:
# shape of the dataframe
df.shape

(3, 3)

# Loading Data

### Load Data from CSV

In [17]:
customers = pd.read_csv('../data/external/customers-100.csv')
customers.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/

### Loading Data from Parquet

In [18]:
olympics = pd.read_parquet('../data/external/olympics.parquet')
olympics.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

### Load Data online

In [19]:
employees = pd.read_csv('https://gist.githubusercontent.com/kevin336/acbb2271e66c10a5b73aacf82ca82784/raw/e38afe62e088394d61ed30884dd50a6826eee0a8/employees.csv')
employees.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600,-,124,50
1,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000,-,100,20
4,202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20

In [20]:
# to select rows with index 1,2,5.
# Note that the index is 0-based, so the row with index 1 is the second row, the row with index 2 is the third row, and the row with index 5 is the sixth row.
# .loc is a label-based indexer used to access rows and columns in a DataFrame by their row labels and column names.
employees = pd.read_csv('../data/external/employees.csv')
employees.loc[[1,2,5]]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
1,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10
5,203,Susan,Mavris,SMAVRIS,515.123.7777,07-JUN-02,HR_REP,6500,-,101,40

In [21]:
# to select rows with index 1 to 5
employees.loc[1:5]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
1,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000,-,100,20
4,202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20
5,203,Susan,Mavris,SMAVRIS,515.123.7777,07-JUN-02,HR_REP,6500,-,101,40

In [22]:
# to select rows with index 5 to 10 and columns 'EMPLOYEE_ID', 'FIRST_NAME', 'LAST_NAME'
employees.loc[5:10, ['EMPLOYEE_ID', 'FIRST_NAME', 'LAST_NAME']]

    EMPLOYEE_ID FIRST_NAME LAST_NAME
5           203      Susan    Mavris
6           204    Hermann      Baer
7           205    Shelley   Higgins
8           206    William     Gietz
9           100     Steven      King
10          101      Neena   Kochhar

In [23]:
# Can change the index to a column name. This is useful when we want to select rows based on a column value.
employees.index = employees.EMPLOYEE_ID
employees.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
EMPLOYEE_ID,,,,,,,,,,,
198,198,Donald,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600,-,124,50
199,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50
200,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10
201,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000,-,100,20
202,202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20

In [24]:
employees.EMPLOYEE_ID = employees.index
employees.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
EMPLOYEE_ID,,,,,,,,,,,
198,198,Donald,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600,-,124,50
199,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50
200,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10
201,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000,-,100,20
202,202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20

In [25]:
# to select rows with index 198 to 203 and columns 'FIRST_NAME', 'LAST_NAME'
employees.loc[198:203, ['FIRST_NAME', 'LAST_NAME']]

            FIRST_NAME  LAST_NAME
EMPLOYEE_ID
198             Donald   OConnell
199            Douglas      Grant
200           Jennifer     Whalen
201            Michael  Hartstein
202                Pat        Fay
203              Susan     Mavris

In [26]:
employees.loc[198, 'FIRST_NAME'] = 'John'
employees.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
EMPLOYEE_ID,,,,,,,,,,,
198,198,John,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600,-,124,50
199,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50
200,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10
201,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000,-,100,20
202,202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20

In [27]:
# set index to a column name and drop the original column. More pandas way to set index instead of assigning to index attribute. (employees.index = employees.EMPLOYEE_ID)
employees.set_index("EMPLOYEE_ID", inplace=True)
employees.head()

,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
EMPLOYEE_ID,,,,,,,,,,
198,John,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600,-,124,50
199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50
200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10
201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000,-,100,20
202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20

In [28]:
# to reset the index to default integer index
employees.reset_index(drop=True, inplace=True)
employees.head()

,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,John,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600,-,124,50
1,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50
2,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10
3,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000,-,100,20
4,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20

In [29]:
# to count the number of occurrences of each unique value in the 'FIRST_NAME' column and display the top 10 most common first names
employees = pd.read_csv('../data/external/employees.csv')
employees.FIRST_NAME.value_counts().head(10)

FIRST_NAME
Michael      2
Steven       2
Alexander    2
John         2
James        2
Donald       1
Douglas      1
Jennifer     1
Pat          1
Susan        1
Name: count, dtype: int64

In [30]:
# to sort the dataframe by FIRST_NAME in ascending order
employees.sort_values(by='FIRST_NAME', inplace=True)
employees.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
30,121,Adam,Fripp,AFRIPP,650.123.2234,10-APR-05,ST_MAN,8200,-,100,50
12,103,Alexander,Hunold,AHUNOLD,590.423.4567,03-JAN-06,IT_PROG,9000,-,102,60
24,115,Alexander,Khoo,AKHOO,515.127.4562,18-MAY-03,PU_CLERK,3100,-,114,30
13,104,Bruce,Ernst,BERNST,590.423.4568,21-MAY-07,IT_PROG,6000,-,103,60
18,109,Daniel,Faviet,DFAVIET,515.124.4169,16-AUG-02,FI_ACCOUNT,9000,-,108,100

In [31]:
# to sort the dataframe by SALARY in descending order and then by FIRST_NAME in ascending order. 
# When two or more rows have the same value in the SALARY column, they will be sorted by FIRST_NAME in ascending order. 
employees.sort_values(['SALARY', 'FIRST_NAME'], ascending=[False, True], inplace=True)
employees[employees.SALARY == 9000].head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
12,103,Alexander,Hunold,AHUNOLD,590.423.4567,03-JAN-06,IT_PROG,9000,-,102,60
18,109,Daniel,Faviet,DFAVIET,515.124.4169,16-AUG-02,FI_ACCOUNT,9000,-,108,100

### Filtering Data

In [32]:
bios = pd.read_csv('../data/external/bios.csv')
bios.tail()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20

In [33]:
# to select rows where height_cm is greater than 210 and born_country is USA, and then select only the name, height_cm and athlete_id columns. 
# Finally, sort the result by height_cm in descending order.
result = bios[(bios['height_cm'] > 210) & (bios['born_country'] == 'USA')][['name', 'height_cm', 'athlete_id']]
result.sort_values(['height_cm'], ascending=[False])
result.head()

                 name  height_cm  athlete_id
5681     Walt Bellamy      211.0        5704
5781   Tommy Burleson      223.0        5804
5894       Mel Counts      213.0        5919
6106  Marc Freiberger      211.0        6133
6281   Darrall Imhoff      211.0        6309

In [34]:
# to select rows where the name column contains either 'Michael' or 'Rahul', ignoring case, and then sort the result by name in ascending order.
bios[bios['name'].str.contains('Michael|Rahul', case=False)].sort_values('name')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
23953,24140,Michael Jackson,1963-11-19,Valença,Rio de Janeiro,BRA,Brazil,168.0,63.0,NaN
25016,25206,Angus Carmichael,1925-06-12,Mamsa,Northern,ZAM,Great Britain,182.0,NaN,2013-03-21
8686,8733,Bill Michaels,1876-07-13,Alcoa,Tennessee,USA,United States,NaN,NaN,1934-01-01
81946,82598,Carl Michaels,1981-05-21,Cape Town,Western Cape,RSA,South Africa,186.0,81.0,NaN
68665,69182,Carmichael Irwin,1894-06-26,Dundrum,Dublin,IRL,Great Britain,NaN,NaN,1930-10-05
...,...,...,...,...,...,...,...,...,...,...
19155,19290,Rahul Singh,1975-01-05,NaN,NaN,NaN,India,NaN,NaN,NaN
110045,111253,Sarah Michael,1990-07-22,Ibadan,Oyo,NGR,Nigeria,172.0,61.0,NaN
62540,63004,Yair Michaeli,1944-09-13,NaN,NaN,NaN,Israel,171.0,68.0,NaN
2908,2920,Yared Woldemichael,1968-01-01,NaN,NaN,NaN,Ethiopia,NaN,NaN,NaN
135403,138617,Zoe Michael,2002-02-03,NaN,NaN,NaN,Australia,NaN,NaN,NaN

In [35]:
# to select rows where the born_country column is either 'USA' or 'GBR', and the name column starts with 'Bill'.
bios[(bios['born_country'].isin(['USA','GBR'])) & (bios['name'].str.startswith('Bill'))]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
3226,3238,Billy Koch,1974-12-14,Rockville Centre,New York,USA,United States,190.0,100.0,NaN
3361,3373,Bill Child,1884-08-07,Swaffham,England,GBR,Great Britain,NaN,NaN,1961-01-01
3372,3384,Bill Dees,1874-09-28,Liverpool,England,GBR,Great Britain,NaN,NaN,1940-10-18
3514,3526,Billy Wells,1936-09-07,London,England,GBR,Great Britain,190.0,84.0,2008-01-01
3925,3939,Billy Barnes,1924-01-01,Belfast,Northern Ireland,GBR,Ireland,NaN,NaN,2006-08-31
...,...,...,...,...,...,...,...,...,...,...
111673,112917,Billy Joe Saunders,1989-08-30,Hatfield,England,GBR,Great Britain,180.0,69.0,NaN
113393,114684,Billy Nelson,1984-09-11,Bakersfield,California,USA,United States,165.0,55.0,NaN
121254,123228,Bill Lucas,1987-09-13,Exeter,England,GBR,Great Britain,199.0,100.0,NaN
125451,127796,Billy Morgan,1989-04-02,Southampton,England,GBR,Great Britain,181.0,72.0,NaN
144650,148346,Billy Major,1996-11-21,Cambridge,England,GBR,Great Britain,NaN,NaN,NaN

In [36]:
# to select rows where the born_country column is either 'USA' or 'GBR', and the name column starts with 'Bill' using query method.
bios.query('born_country in ["USA", "GBR"] and name.str.startswith("Bill")')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
3226,3238,Billy Koch,1974-12-14,Rockville Centre,New York,USA,United States,190.0,100.0,NaN
3361,3373,Bill Child,1884-08-07,Swaffham,England,GBR,Great Britain,NaN,NaN,1961-01-01
3372,3384,Bill Dees,1874-09-28,Liverpool,England,GBR,Great Britain,NaN,NaN,1940-10-18
3514,3526,Billy Wells,1936-09-07,London,England,GBR,Great Britain,190.0,84.0,2008-01-01
3925,3939,Billy Barnes,1924-01-01,Belfast,Northern Ireland,GBR,Ireland,NaN,NaN,2006-08-31
...,...,...,...,...,...,...,...,...,...,...
111673,112917,Billy Joe Saunders,1989-08-30,Hatfield,England,GBR,Great Britain,180.0,69.0,NaN
113393,114684,Billy Nelson,1984-09-11,Bakersfield,California,USA,United States,165.0,55.0,NaN
121254,123228,Bill Lucas,1987-09-13,Exeter,England,GBR,Great Britain,199.0,100.0,NaN
125451,127796,Billy Morgan,1989-04-02,Southampton,England,GBR,Great Britain,181.0,72.0,NaN
144650,148346,Billy Major,1996-11-21,Cambridge,England,GBR,Great Britain,NaN,NaN,NaN

### Adding/Removing Columns

In [39]:
people = pd.read_csv('../data/external/some-people.csv')
people.head()

      name  age born_country
0    Alice   30          USA
1      Bob   25          GBR
2  Charlie   35          CAN
3    David   28          USA
4      Eve   22          GBR

In [42]:
# to add a new column 'year' to the dataframe and set its value to 1985 for all rows.
people['year'] = 1985
people.head()

      name  age born_country  year
0    Alice   30          USA  1985
1      Bob   25          GBR  1985
2  Charlie   35          CAN  1985
3    David   28          USA  1985
4      Eve   22          GBR  1985

In [ ]:
import numpy as np
people[]