# Pandas Operations

### Simple Operations

In [1]:
import pandas as pd
df = pd.DataFrame([[1,2,3],[3,4,5],[5,6,7]], columns=['A','B','C'], index=['x','y','z'])

In [2]:
print(df)

   A  B  C
x  1  2  3
y  3  4  5
z  5  6  7

In [3]:
df.tail(2)

   A  B  C
y  3  4  5
z  5  6  7

In [4]:
df.index.tolist()

['x', 'y', 'z']

In [5]:
df.info()

<class 'pandas.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 99.0 bytes

In [6]:
print(df)

   A  B  C
x  1  2  3
y  3  4  5
z  5  6  7

In [7]:
df = pd.DataFrame([[1,2,0],[3,4,5],[5,0,7]], columns=['D','E','F'], index=['x','y','z'])
print(df)

   D  E  F
x  1  2  0
y  3  4  5
z  5  0  7

In [8]:
df.info()

<class 'pandas.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   D       3 non-null      int64
 1   E       3 non-null      int64
 2   F       3 non-null      int64
dtypes: int64(3)
memory usage: 99.0 bytes

In [9]:
import numpy as np
df = pd.DataFrame([[1,2,np.nan],[3,np.nan,5],[5,6,7]], columns=['A','B','C'], index=['x','y','z'])
print(df)

   A    B    C
x  1  2.0  NaN
y  3  NaN  5.0
z  5  6.0  7.0

In [10]:
df.info()

<class 'pandas.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       2 non-null      float64
 2   C       2 non-null      float64
dtypes: float64(2), int64(1)
memory usage: 99.0 bytes

In [11]:
# describe() gives us the count, mean, std, min, 25%, 50%, 75% and max values for each column in the dataframe
df.describe()

         A         B         C
count  3.0  2.000000  2.000000
mean   3.0  4.000000  6.000000
std    2.0  2.828427  1.414214
min    1.0  2.000000  5.000000
25%    2.0  3.000000  5.500000
50%    3.0  4.000000  6.000000
75%    4.0  5.000000  6.500000
max    5.0  6.000000  7.000000

In [12]:
# number of unique values in each column
df.nunique()

A    3
B    2
C    2
dtype: int64

In [13]:
print(df)

   A    B    C
x  1  2.0  NaN
y  3  NaN  5.0
z  5  6.0  7.0

In [14]:
# unique values in column A
df['A'].unique()

array([1, 3, 5])

In [15]:
# shape of the dataframe
df.shape

(3, 3)

# Loading Data

### Load Data from CSV

In [16]:
customers = pd.read_csv('../data/external/customers-100.csv')
customers.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/

### Loading Data from Parquet

In [17]:
olympics = pd.read_parquet('../data/external/olympics.parquet')
olympics.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

### Load Data online

In [18]:
employees = pd.read_csv('https://gist.githubusercontent.com/kevin336/acbb2271e66c10a5b73aacf82ca82784/raw/e38afe62e088394d61ed30884dd50a6826eee0a8/employees.csv')
employees.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600,-,124,50
1,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000,-,100,20
4,202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20

In [19]:
# to select rows with index 1,2,5.
# Note that the index is 0-based, so the row with index 1 is the second row, the row with index 2 is the third row, and the row with index 5 is the sixth row.
# .loc is a label-based indexer used to access rows and columns in a DataFrame by their row labels and column names.
employees = pd.read_csv('../data/external/employees.csv')
employees.loc[[1,2,5]]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
1,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10
5,203,Susan,Mavris,SMAVRIS,515.123.7777,07-JUN-02,HR_REP,6500,-,101,40

In [20]:
# to select rows with index 1 to 5
employees.loc[1:5]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
1,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000,-,100,20
4,202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20
5,203,Susan,Mavris,SMAVRIS,515.123.7777,07-JUN-02,HR_REP,6500,-,101,40

In [21]:
# to select rows with index 5 to 10 and columns 'EMPLOYEE_ID', 'FIRST_NAME', 'LAST_NAME'
employees.loc[5:10, ['EMPLOYEE_ID', 'FIRST_NAME', 'LAST_NAME']]

    EMPLOYEE_ID FIRST_NAME LAST_NAME
5           203      Susan    Mavris
6           204    Hermann      Baer
7           205    Shelley   Higgins
8           206    William     Gietz
9           100     Steven      King
10          101      Neena   Kochhar

In [22]:
# Can change the index to a column name. This is useful when we want to select rows based on a column value.
employees.index = employees.EMPLOYEE_ID
employees.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
EMPLOYEE_ID,,,,,,,,,,,
198,198,Donald,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600,-,124,50
199,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50
200,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10
201,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000,-,100,20
202,202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20

In [23]:
employees.EMPLOYEE_ID = employees.index
employees.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
EMPLOYEE_ID,,,,,,,,,,,
198,198,Donald,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600,-,124,50
199,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50
200,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10
201,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000,-,100,20
202,202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20

In [24]:
# to select rows with index 198 to 203 and columns 'FIRST_NAME', 'LAST_NAME'
employees.loc[198:203, ['FIRST_NAME', 'LAST_NAME']]

            FIRST_NAME  LAST_NAME
EMPLOYEE_ID
198             Donald   OConnell
199            Douglas      Grant
200           Jennifer     Whalen
201            Michael  Hartstein
202                Pat        Fay
203              Susan     Mavris

In [25]:
employees.loc[198, 'FIRST_NAME'] = 'John'
employees.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
EMPLOYEE_ID,,,,,,,,,,,
198,198,John,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600,-,124,50
199,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50
200,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10
201,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000,-,100,20
202,202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20

In [26]:
# set index to a column name and drop the original column. More pandas way to set index instead of assigning to index attribute. (employees.index = employees.EMPLOYEE_ID)
employees.set_index("EMPLOYEE_ID", inplace=True)
employees.head()

,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
EMPLOYEE_ID,,,,,,,,,,
198,John,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600,-,124,50
199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50
200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10
201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000,-,100,20
202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20

In [27]:
# to reset the index to default integer index
employees.reset_index(drop=True, inplace=True)
employees.head()

,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,John,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600,-,124,50
1,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50
2,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10
3,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000,-,100,20
4,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20

In [28]:
# to count the number of occurrences of each unique value in the 'FIRST_NAME' column and display the top 10 most common first names
employees = pd.read_csv('../data/external/employees.csv')
employees.FIRST_NAME.value_counts().head(10)

FIRST_NAME
Michael      2
Steven       2
Alexander    2
John         2
James        2
Donald       1
Douglas      1
Jennifer     1
Pat          1
Susan        1
Name: count, dtype: int64

In [29]:
# to sort the dataframe by FIRST_NAME in ascending order
employees.sort_values(by='FIRST_NAME', inplace=True)
employees.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
30,121,Adam,Fripp,AFRIPP,650.123.2234,10-APR-05,ST_MAN,8200,-,100,50
12,103,Alexander,Hunold,AHUNOLD,590.423.4567,03-JAN-06,IT_PROG,9000,-,102,60
24,115,Alexander,Khoo,AKHOO,515.127.4562,18-MAY-03,PU_CLERK,3100,-,114,30
13,104,Bruce,Ernst,BERNST,590.423.4568,21-MAY-07,IT_PROG,6000,-,103,60
18,109,Daniel,Faviet,DFAVIET,515.124.4169,16-AUG-02,FI_ACCOUNT,9000,-,108,100

In [30]:
# to sort the dataframe by SALARY in descending order and then by FIRST_NAME in ascending order. 
# When two or more rows have the same value in the SALARY column, they will be sorted by FIRST_NAME in ascending order. 
employees.sort_values(['SALARY', 'FIRST_NAME'], ascending=[False, True], inplace=True)
employees[employees.SALARY == 9000].head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
12,103,Alexander,Hunold,AHUNOLD,590.423.4567,03-JAN-06,IT_PROG,9000,-,102,60
18,109,Daniel,Faviet,DFAVIET,515.124.4169,16-AUG-02,FI_ACCOUNT,9000,-,108,100

### Filtering Data

In [31]:
bios = pd.read_csv('../data/external/bios.csv')
bios.tail()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20

In [32]:
# to select rows where height_cm is greater than 210 and born_country is USA, and then select only the name, height_cm and athlete_id columns. 
# Finally, sort the result by height_cm in descending order.
result = bios[(bios['height_cm'] > 210) & (bios['born_country'] == 'USA')][['name', 'height_cm', 'athlete_id']]
result.sort_values(['height_cm'], ascending=[False])
result.head()

                 name  height_cm  athlete_id
5681     Walt Bellamy      211.0        5704
5781   Tommy Burleson      223.0        5804
5894       Mel Counts      213.0        5919
6106  Marc Freiberger      211.0        6133
6281   Darrall Imhoff      211.0        6309

In [33]:
# to select rows where the name column contains either 'Michael' or 'Rahul', ignoring case, and then sort the result by name in ascending order.
bios[bios['name'].str.contains('Michael|Rahul', case=False)].sort_values('name')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
23953,24140,Michael Jackson,1963-11-19,Valença,Rio de Janeiro,BRA,Brazil,168.0,63.0,NaN
25016,25206,Angus Carmichael,1925-06-12,Mamsa,Northern,ZAM,Great Britain,182.0,NaN,2013-03-21
8686,8733,Bill Michaels,1876-07-13,Alcoa,Tennessee,USA,United States,NaN,NaN,1934-01-01
81946,82598,Carl Michaels,1981-05-21,Cape Town,Western Cape,RSA,South Africa,186.0,81.0,NaN
68665,69182,Carmichael Irwin,1894-06-26,Dundrum,Dublin,IRL,Great Britain,NaN,NaN,1930-10-05
...,...,...,...,...,...,...,...,...,...,...
19155,19290,Rahul Singh,1975-01-05,NaN,NaN,NaN,India,NaN,NaN,NaN
110045,111253,Sarah Michael,1990-07-22,Ibadan,Oyo,NGR,Nigeria,172.0,61.0,NaN
62540,63004,Yair Michaeli,1944-09-13,NaN,NaN,NaN,Israel,171.0,68.0,NaN
2908,2920,Yared Woldemichael,1968-01-01,NaN,NaN,NaN,Ethiopia,NaN,NaN,NaN
135403,138617,Zoe Michael,2002-02-03,NaN,NaN,NaN,Australia,NaN,NaN,NaN

In [34]:
# to select rows where the born_country column is either 'USA' or 'GBR', and the name column starts with 'Bill'.
bios[(bios['born_country'].isin(['USA','GBR'])) & (bios['name'].str.startswith('Bill'))]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
3226,3238,Billy Koch,1974-12-14,Rockville Centre,New York,USA,United States,190.0,100.0,NaN
3361,3373,Bill Child,1884-08-07,Swaffham,England,GBR,Great Britain,NaN,NaN,1961-01-01
3372,3384,Bill Dees,1874-09-28,Liverpool,England,GBR,Great Britain,NaN,NaN,1940-10-18
3514,3526,Billy Wells,1936-09-07,London,England,GBR,Great Britain,190.0,84.0,2008-01-01
3925,3939,Billy Barnes,1924-01-01,Belfast,Northern Ireland,GBR,Ireland,NaN,NaN,2006-08-31
...,...,...,...,...,...,...,...,...,...,...
111673,112917,Billy Joe Saunders,1989-08-30,Hatfield,England,GBR,Great Britain,180.0,69.0,NaN
113393,114684,Billy Nelson,1984-09-11,Bakersfield,California,USA,United States,165.0,55.0,NaN
121254,123228,Bill Lucas,1987-09-13,Exeter,England,GBR,Great Britain,199.0,100.0,NaN
125451,127796,Billy Morgan,1989-04-02,Southampton,England,GBR,Great Britain,181.0,72.0,NaN
144650,148346,Billy Major,1996-11-21,Cambridge,England,GBR,Great Britain,NaN,NaN,NaN

In [35]:
# to select rows where the born_country column is either 'USA' or 'GBR', and the name column starts with 'Bill' using query method.
bios.query('born_country in ["USA", "GBR"] and name.str.startswith("Bill")')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
3226,3238,Billy Koch,1974-12-14,Rockville Centre,New York,USA,United States,190.0,100.0,NaN
3361,3373,Bill Child,1884-08-07,Swaffham,England,GBR,Great Britain,NaN,NaN,1961-01-01
3372,3384,Bill Dees,1874-09-28,Liverpool,England,GBR,Great Britain,NaN,NaN,1940-10-18
3514,3526,Billy Wells,1936-09-07,London,England,GBR,Great Britain,190.0,84.0,2008-01-01
3925,3939,Billy Barnes,1924-01-01,Belfast,Northern Ireland,GBR,Ireland,NaN,NaN,2006-08-31
...,...,...,...,...,...,...,...,...,...,...
111673,112917,Billy Joe Saunders,1989-08-30,Hatfield,England,GBR,Great Britain,180.0,69.0,NaN
113393,114684,Billy Nelson,1984-09-11,Bakersfield,California,USA,United States,165.0,55.0,NaN
121254,123228,Bill Lucas,1987-09-13,Exeter,England,GBR,Great Britain,199.0,100.0,NaN
125451,127796,Billy Morgan,1989-04-02,Southampton,England,GBR,Great Britain,181.0,72.0,NaN
144650,148346,Billy Major,1996-11-21,Cambridge,England,GBR,Great Britain,NaN,NaN,NaN

## Adding/Removing Columns

In [36]:
people = pd.read_csv('../data/external/some-people.csv')
people.head()

      name  age born_country
0    Alice   30          USA
1      Bob   25          GBR
2  Charlie   35          CAN
3    David   28          USA
4      Eve   22          GBR

In [37]:
# to add a new column 'year' to the dataframe and set its value to 1985 for all rows.
people['year'] = 1985
people.head()

      name  age born_country  year
0    Alice   30          USA  1985
1      Bob   25          GBR  1985
2  Charlie   35          CAN  1985
3    David   28          USA  1985
4      Eve   22          GBR  1985

In [38]:
import numpy as np
people['actual_year'] = np.where(people['born_country'] == 'USA', 2000, 2010)
people.head()

      name  age born_country  year  actual_year
0    Alice   30          USA  1985         2000
1      Bob   25          GBR  1985         2010
2  Charlie   35          CAN  1985         2010
3    David   28          USA  1985         2000
4      Eve   22          GBR  1985         2010

In [39]:
# to drop the 'year' column from the dataframe. This will return a new dataframe without the 'year' column, but it will not modify the original dataframe unless we set inplace=True.
people.drop(columns=['year'])
people.head(4)

      name  age born_country  year  actual_year
0    Alice   30          USA  1985         2000
1      Bob   25          GBR  1985         2010
2  Charlie   35          CAN  1985         2010
3    David   28          USA  1985         2000

In [40]:
people.head(2)

    name  age born_country  year  actual_year
0  Alice   30          USA  1985         2000
1    Bob   25          GBR  1985         2010

In [41]:
# to add a new column 'age_after_5years' to the dataframe, which is the age of the person after 5 years. This is done by adding 5 to the 'age' column.
people['age_after_5years'] = people['age'] + 5
people.head(2)

    name  age born_country  year  actual_year  age_after_5years
0  Alice   30          USA  1985         2000                35
1    Bob   25          GBR  1985         2010                30

In [42]:
# to rename the column 'age_after_5years' to 'age_in_5_years'. This will modify the original dataframe because we set inplace=True.
people.rename(columns={'age_after_5years': 'age_in_5_years'}, inplace=True)
people.head(2)

    name  age born_country  year  actual_year  age_in_5_years
0  Alice   30          USA  1985         2000              35
1    Bob   25          GBR  1985         2010              30

In [43]:
# to select rows where the first name is 'Albert'. We will first create a new column 'first_name' by splitting the 'name' column and taking the first part of the name. 
# Then we will filter the rows where 'first_name' is 'Albert'.
bios_new = bios.copy()
bios_new['first_name'] = bios_new['name'].str.split().str[0]
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert

In [44]:
# to select rows where the first name is 'Albert'.
bios_new.loc[bios_new['first_name'] == "Albert"]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert
28,29,Albert Lippmann,NaN,NaN,NaN,NaN,France,NaN,NaN,NaN,Albert
461,462,Albert Dauchez,NaN,NaN,NaN,NaN,France,NaN,NaN,NaN,Albert
480,481,Albert le Tyrant,1946-09-12,NaN,NaN,NaN,France,170.0,70.0,NaN,Albert
678,681,Albert Lammens,1890-06-17,Bruxelles (Brussels),Région de Bruxelles-Capitale,BEL,Belgium,NaN,NaN,1933-10-07,Albert
...,...,...,...,...,...,...,...,...,...,...,...
138515,141924,Albert Mengue,1999-04-18,NaN,NaN,NaN,Cameroon,NaN,NaN,NaN,Albert
139097,142547,Albert Beltrán,1993-10-23,Sabadell,Barcelona,ESP,Spain,179.0,73.0,NaN,Albert
142610,146223,Albert Batyrgaziyev,1998-06-23,Babayurt,Respublika Dagestan,RUS,ROC,NaN,NaN,NaN,Albert
143350,146994,Albert Chemutai,1999-11-25,NaN,NaN,NaN,Uganda,NaN,NaN,NaN,Albert
144702,148402,Albert Kuchler,1998-11-30,Bad Kötzting,Bayern,GER,Germany,NaN,NaN,NaN,Albert

In [45]:
# to create a new column 'born_datetime' by converting the 'born_date' column to a datetime object. 
# Then we will extract the year from the 'born_datetime' column and store it in a new column 'born_year'.
bios_new['born_datetime'] = pd.to_datetime(bios_new['born_date'], format='%Y-%m-%d')
bios_new['born_year'] = bios_new['born_datetime'].dt.year
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime,born_year
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01,1969.0
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13,1898.0
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895.0
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17,1878.0

#### Save dataframe to new csv file

In [46]:
# to save the modified dataframe to a new CSV file called 'bios_new.csv' in the 'processed' folder. 
# We will set index=False to avoid saving the index as a separate column in the CSV file.
bios_new.to_csv('../data/processed/bios_new.csv', index=False)

In [47]:
# to create a new column 'height_category' based on the values in the 'height_cm' column.
bios_new['height_category'] = bios_new['height_cm'].apply(lambda x: 'Short' if x<165 else 'Average' if x<185 else 'Tall')
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime,born_year,height_category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0,Tall
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01,1969.0,Average
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13,1898.0,Average
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895.0,Average
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17,1878.0,Tall

In [48]:
# to create a new column 'weight_category' based on the values in the 'weight_kg' column. 
# We will use the apply method to apply a function that categorizes the weight into 'Lightweight', 'Middleweight' and 'Heavyweight'. 
# axis=1 is used to apply the function to each row of the dataframe. 
def categorize_height(row):
    if row['height_cm'] < 165 and row['weight_kg'] < 70:
        return 'Lightweight'
    elif row['height_cm'] < 185 and row['weight_kg'] < 85:
        return 'Middleweight'
    else:
        return 'Heavyweight'
    
bios_new['weight_category'] = bios_new.apply(categorize_height, axis=1)
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime,born_year,height_category,weight_category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0,Tall,Heavyweight
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01,1969.0,Average,Middleweight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13,1898.0,Average,Middleweight
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895.0,Average,Middleweight
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17,1878.0,Tall,Heavyweight

## Merging and Concatenating Data

In [49]:
nocs = pd.read_csv('../data/external/noc_regions.csv')
bios = pd.read_csv('../data/external/bios.csv')

In [50]:
# to merge the bios and nocs dataframes on the born_country and NOC columns respectively. 
# We will use a left join to keep all the rows from the bios dataframe and add the corresponding region information from the nocs dataframe.
bios_new = pd.merge(bios, nocs, left_on='born_country', right_on='NOC', how='left')
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,NOC_y,region,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,FRA,France,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,FRA,France,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,FRA,France,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,FRA,France,NaN
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,GBR,UK,NaN

In [51]:
# to select rows where the NOC_x column (which is the born_country from bios) is not equal to the region column (which is the region from nocs).
bios_new[bios_new['NOC_x'] != bios_new['region']][['name', 'born_country', 'NOC_x', 'region']]

                       name born_country    NOC_x   region
4              Albert Canet          GBR   France       UK
12                J. Defert          NaN   France      NaN
13           Étienne Durand          NaN   France      NaN
16               Guy Forget          MAR   France  Morocco
27       Guy, Baron Lejeune          NaN   France      NaN
...                     ...          ...      ...      ...
145491        Matthew Wepke          NaN  Jamaica      NaN
145493   Landysh Falyakhova          RUS      ROC   Russia
145495    Polina Luchnikova          RUS      ROC   Russia
145496  Valeriya Merkusheva          RUS      ROC   Russia
145497      Yuliya Smirnova          RUS      ROC   Russia

[73210 rows x 4 columns]

In [ ]:
# to select rows where the born_country column is either 'USA' or 'GBR', 
# and then concatenate the resulting dataframes for USA and GBR into a new dataframe called new_df.
usa = bios_new[bios_new['born_country'] == 'USA']
gbr = bios_new[bios_new['born_country'] == 'GBR']

new_df = pd.concat([usa, gbr], ignore_index=True)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,NOC_y,region,notes
15428,148512,Benjamin Alexander,1983-05-08,London,England,GBR,Jamaica,NaN,NaN,NaN,GBR,UK,NaN
15429,148517,Ashley Watson,1993-10-28,Peterborough,England,GBR,Jamaica,NaN,NaN,NaN,GBR,UK,NaN
15430,148716,Peder Kongshaug,2001-08-13,Wimbledon,England,GBR,Norway,184.0,86.0,NaN,GBR,UK,NaN
15431,149041,Axel Brown,1992-04-02,Harrogate,England,GBR,Trinidad and Tobago,NaN,NaN,NaN,GBR,UK,NaN
15432,149111,Jean-Luc Baker,1993-10-07,Burnley,England,GBR,United States,NaN,NaN,NaN,GBR,UK,NaN

In [ ]:
# to display the first 2 rows of the new_df dataframe with USA and GBR athletes.
new_df.head(2)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,NOC_y,region,notes
0,55,Monique Javer,1967-07-22,Burlingame,California,USA,Great Britain,177.0,64.0,NaN,USA,USA,NaN
1,964,Xóchitl Escobedo,1968-09-17,West Covina,California,USA,Mexico,170.0,60.0,NaN,USA,USA,NaN

In [56]:
# to display the last 2 rows of the new_df dataframe with USA and GBR athletes.
new_df.tail(2)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,NOC_y,region,notes
15431,149041,Axel Brown,1992-04-02,Harrogate,England,GBR,Trinidad and Tobago,NaN,NaN,NaN,GBR,UK,NaN
15432,149111,Jean-Luc Baker,1993-10-07,Burnley,England,GBR,United States,NaN,NaN,NaN,GBR,UK,NaN

In [61]:
result = pd.read_csv('../data/external/results.csv')
combined_df = pd.merge(result, new_df, on='athlete_id', how='left')
combined_df.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,...,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,NOC_y,region,notes
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN