# Pandas Operations

In [1]:
import pandas as pd
df = pd.DataFrame([[1,2,3],[3,4,5],[5,6,7]], columns=['A','B','C'], index=['x','y','z'])

In [2]:
print(df)

   A  B  C
x  1  2  3
y  3  4  5
z  5  6  7

In [3]:
df.tail(2)

   A  B  C
y  3  4  5
z  5  6  7

In [4]:
df.index.tolist()

['x', 'y', 'z']

In [5]:
df.info()

<class 'pandas.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 99.0 bytes

In [6]:
print(df)

   A  B  C
x  1  2  3
y  3  4  5
z  5  6  7

In [7]:
df = pd.DataFrame([[1,2,0],[3,4,5],[5,0,7]], columns=['D','E','F'], index=['x','y','z'])
print(df)

   D  E  F
x  1  2  0
y  3  4  5
z  5  0  7

In [8]:
df.info()

<class 'pandas.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   D       3 non-null      int64
 1   E       3 non-null      int64
 2   F       3 non-null      int64
dtypes: int64(3)
memory usage: 99.0 bytes

In [9]:
import numpy as np
df = pd.DataFrame([[1,2,np.nan],[3,np.nan,5],[5,6,7]], columns=['A','B','C'], index=['x','y','z'])
print(df)

   A    B    C
x  1  2.0  NaN
y  3  NaN  5.0
z  5  6.0  7.0

In [10]:
df.info()

<class 'pandas.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       2 non-null      float64
 2   C       2 non-null      float64
dtypes: float64(2), int64(1)
memory usage: 99.0 bytes

In [11]:
df.describe()

         A         B         C
count  3.0  2.000000  2.000000
mean   3.0  4.000000  6.000000
std    2.0  2.828427  1.414214
min    1.0  2.000000  5.000000
25%    2.0  3.000000  5.500000
50%    3.0  4.000000  6.000000
75%    4.0  5.000000  6.500000
max    5.0  6.000000  7.000000

In [12]:
df.nunique()

A    3
B    2
C    2
dtype: int64

In [13]:
print(df)

   A    B    C
x  1  2.0  NaN
y  3  NaN  5.0
z  5  6.0  7.0

In [14]:
df['A'].unique()

array([1, 3, 5])

In [15]:
df.shape

(3, 3)

# **Loading Data from CSV**

In [16]:
customers = pd.read_csv('../data/external/customers-100.csv')
customers.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/

### Load Data online

In [17]:
employees = pd.read_csv('https://gist.githubusercontent.com/kevin336/acbb2271e66c10a5b73aacf82ca82784/raw/e38afe62e088394d61ed30884dd50a6826eee0a8/employees.csv')
employees.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600,-,124,50
1,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000,-,100,20
4,202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20

### **Loading Data from Parquet**

In [18]:
olympics = pd.read_parquet('../data/external/olympics.parquet')
olympics.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

In [19]:
customers.head(2)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/

In [20]:
# to select rows with index 1,2,5
employees.loc[[1,2,5]]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
1,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10
5,203,Susan,Mavris,SMAVRIS,515.123.7777,07-JUN-02,HR_REP,6500,-,101,40

In [21]:
# to select rows with index 1 to 5
employees.loc[1:5]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
1,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000,-,100,20
4,202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20
5,203,Susan,Mavris,SMAVRIS,515.123.7777,07-JUN-02,HR_REP,6500,-,101,40

In [22]:
# to select rows with index 5 to 10 and columns 'EMPLOYEE_ID', 'FIRST_NAME', 'LAST_NAME'
employees.loc[5:10, ['EMPLOYEE_ID', 'FIRST_NAME', 'LAST_NAME']]

    EMPLOYEE_ID FIRST_NAME LAST_NAME
5           203      Susan    Mavris
6           204    Hermann      Baer
7           205    Shelley   Higgins
8           206    William     Gietz
9           100     Steven      King
10          101      Neena   Kochhar

In [23]:
# Can change the index to a column name. This is useful when we want to select rows based on a column value.
employees.index = employees.EMPLOYEE_ID
employees.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
EMPLOYEE_ID,,,,,,,,,,,
198,198,Donald,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600,-,124,50
199,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50
200,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10
201,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000,-,100,20
202,202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20

In [24]:
# to select rows with index 198 to 203 and columns 'FIRST_NAME', 'LAST_NAME'
employees.loc[198:203, ['FIRST_NAME', 'LAST_NAME']]

            FIRST_NAME  LAST_NAME
EMPLOYEE_ID
198             Donald   OConnell
199            Douglas      Grant
200           Jennifer     Whalen
201            Michael  Hartstein
202                Pat        Fay
203              Susan     Mavris

In [25]:
employees.loc[198, 'FIRST_NAME'] = 'John'
employees.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
EMPLOYEE_ID,,,,,,,,,,,
198,198,John,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600,-,124,50
199,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50
200,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10
201,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000,-,100,20
202,202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20

In [26]:
# set index to a column name and drop the original column. More pandas way to set index instead of assigning to index attribute. (employees.index = employees.EMPLOYEE_ID)
employees.set_index("EMPLOYEE_ID", inplace=True)
employees.head()

,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
EMPLOYEE_ID,,,,,,,,,,
198,John,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600,-,124,50
199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50
200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10
201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000,-,100,20
202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20

In [27]:
# to reset the index to default integer index
employees.reset_index(drop=True, inplace=True)
employees.head()

,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,John,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600,-,124,50
1,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50
2,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10
3,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000,-,100,20
4,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20