# Pandas Operations

### Simple Operations

In [230]:
import pandas as pd
df = pd.DataFrame([[1,2,3],[3,4,5],[5,6,7]], columns=['A','B','C'], index=['x','y','z'])
df

   A  B  C
x  1  2  3
y  3  4  5
z  5  6  7

In [231]:
# to create a DataFrame from a dictionary of lists.
import pandas as pd

data = {
    "Name": ["Akshay", "Rahul", "Priya"],
    "Age": [25, 28, 24]
}

df = pd.DataFrame(data)

print(df)

     Name  Age
0  Akshay   25
1   Rahul   28
2   Priya   24

In [232]:
df.tail(2)

    Name  Age
1  Rahul   28
2  Priya   24

In [233]:
df.index.tolist()

[0, 1, 2]

In [234]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      int64
dtypes: int64(1), str(1)
memory usage: 196.0 bytes

In [235]:
print(df)

     Name  Age
0  Akshay   25
1   Rahul   28
2   Priya   24

In [236]:
df = pd.DataFrame([[1,2,0],[3,4,5],[5,0,7]], columns=['D','E','F'], index=['x','y','z'])
print(df)

   D  E  F
x  1  2  0
y  3  4  5
z  5  0  7

In [237]:
df.info()

<class 'pandas.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   D       3 non-null      int64
 1   E       3 non-null      int64
 2   F       3 non-null      int64
dtypes: int64(3)
memory usage: 99.0 bytes

In [238]:
# create dataframe with null values using numpy library
import numpy as np
df = pd.DataFrame([[1,2,np.nan],[3,np.nan,5],[5,6,7]], columns=['A','B','C'], index=['x','y','z'])
print(df)

   A    B    C
x  1  2.0  NaN
y  3  NaN  5.0
z  5  6.0  7.0

In [239]:
df.info()

<class 'pandas.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       2 non-null      float64
 2   C       2 non-null      float64
dtypes: float64(2), int64(1)
memory usage: 99.0 bytes

In [240]:
# describe() gives us the count, mean, std, min, 25%, 50%, 75% and max values for each column in the dataframe
df.describe()

         A         B         C
count  3.0  2.000000  2.000000
mean   3.0  4.000000  6.000000
std    2.0  2.828427  1.414214
min    1.0  2.000000  5.000000
25%    2.0  3.000000  5.500000
50%    3.0  4.000000  6.000000
75%    4.0  5.000000  6.500000
max    5.0  6.000000  7.000000

In [241]:
# number of unique values in each column
df.nunique()

A    3
B    2
C    2
dtype: int64

In [242]:
print(df)

   A    B    C
x  1  2.0  NaN
y  3  NaN  5.0
z  5  6.0  7.0

In [243]:
# unique values in column A
df['A'].unique()

array([1, 3, 5])

In [244]:
# shape of the dataframe
df.shape

(3, 3)

### Load Data from CSV

In [245]:
customers = pd.read_csv('../data/external/customers-100.csv')
customers.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/

### Loading Data from Parquet

In [246]:
olympics = pd.read_parquet('../data/external/olympics.parquet')
olympics.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

### Load Data online

In [247]:
employees = pd.read_csv('https://gist.githubusercontent.com/kevin336/acbb2271e66c10a5b73aacf82ca82784/raw/e38afe62e088394d61ed30884dd50a6826eee0a8/employees.csv')
employees.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600,-,124,50
1,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000,-,100,20
4,202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20

### Label-based selection

In [248]:
# to set the index to desired column
employees.set_index('EMPLOYEE_ID', inplace=True)
employees.head()

,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
EMPLOYEE_ID,,,,,,,,,,
198,Donald,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600,-,124,50
199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50
200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10
201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000,-,100,20
202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20

In [249]:
# to reset the index to default integer index. Important, with 'drop=True' the index is removed permanently.
# here 'EMPLOYEE_ID' is lost and will need to load the df again to bring it back.
employees.reset_index(drop=True, inplace=True)
employees.head()

,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,Donald,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600,-,124,50
1,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50
2,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10
3,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000,-,100,20
4,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20

In [250]:
# to select rows with index 1,2,5.
# Note that the index is 0-based, so the row with index 1 is the second row, the row with index 2 is the third row, 
# and the row with index 5 is the sixth row.
# .loc is a label-based indexer used to access rows and columns in a DataFrame by their row labels and column names.
# df.loc[rows, columns] OR with condition: df.loc[boolean_condition]
employees = pd.read_csv('../data/external/employees.csv')
employees.loc[[1,2,5]]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
1,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10
5,203,Susan,Mavris,SMAVRIS,515.123.7777,07-JUN-02,HR_REP,6500,-,101,40

In [251]:
employees.loc[[1,2,3], ['FIRST_NAME']]

  FIRST_NAME
1    Douglas
2   Jennifer
3    Michael

In [252]:
# to select rows with index 1 to 5 and columns between FIRST_NAME and EMAIL
employees.loc[1:5, 'FIRST_NAME':'EMAIL']

  FIRST_NAME  LAST_NAME     EMAIL
1    Douglas      Grant    DGRANT
2   Jennifer     Whalen   JWHALEN
3    Michael  Hartstein  MHARTSTE
4        Pat        Fay      PFAY
5      Susan     Mavris   SMAVRIS

In [253]:
# to select rows with index 5 to 10 and columns 'EMPLOYEE_ID', 'FIRST_NAME', 'LAST_NAME'
employees.loc[5:10, ['EMPLOYEE_ID', 'FIRST_NAME', 'LAST_NAME']]

    EMPLOYEE_ID FIRST_NAME LAST_NAME
5           203      Susan    Mavris
6           204    Hermann      Baer
7           205    Shelley   Higgins
8           206    William     Gietz
9           100     Steven      King
10          101      Neena   Kochhar

In [254]:
# to select rows with EMPLOYEE ID 198 to 203 and as index and columns 'FIRST_NAME', 'LAST_NAME'
employees.set_index('EMPLOYEE_ID', inplace=True)
employees.loc[198:203, ['FIRST_NAME', 'LAST_NAME']]

            FIRST_NAME  LAST_NAME
EMPLOYEE_ID
198             Donald   OConnell
199            Douglas      Grant
200           Jennifer     Whalen
201            Michael  Hartstein
202                Pat        Fay
203              Susan     Mavris

In [255]:
# to change the value of the 'FIRST_NAME' column for the row with index 198 to 'John'. 198 is index which didn't existed earlier but was created after below code. 
# It's not referring to EMPLOYEE_ID=198
employees.reset_index(inplace=True)
employees.loc[198, 'FIRST_NAME'] = 'John'
employees.loc[198]

EMPLOYEE_ID        NaN
FIRST_NAME        John
LAST_NAME          NaN
EMAIL              NaN
PHONE_NUMBER       NaN
HIRE_DATE          NaN
JOB_ID             NaN
SALARY             NaN
COMMISSION_PCT     NaN
MANAGER_ID         NaN
DEPARTMENT_ID      NaN
Name: 198, dtype: object

In [256]:
# VERY IMPORTANT: filter records based on any record value
# Below code is equivalent to..
# Show rows where:
#    name starts with "Andy"
# Adding na=False inside .str.contains() is a good habit. If your CSV has any missing or blank values (NaN) in the name column, it prevents the code from crashing with an error.
import pandas as pd
customer = pd.read_csv('../data/external/bios.csv')
filtered = customer.loc[customer['name'].str.startswith('Andy', na=False)] # OR filtered = customer.loc[customer['height_cm'] == 183.0]
filtered

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
95,96,Andy Goode,1960-01-30,Welwyn Garden City,England,GBR,Great Britain,183.0,83.0,NaN
3490,3502,Andy Straughn,1961-05-11,NaN,NaN,NaN,Great Britain,190.0,81.0,NaN
5796,5819,Andy Campbell,1956-07-21,Melbourne,Victoria,AUS,Australia,218.0,93.0,NaN
5942,5968,Andy dela Cruz,1923-11-10,Pasay City,Manila,PHI,Philippines,NaN,NaN,1993-06-05
7770,7811,Andy Agosto,1970-09-11,Carolina,Puerto Rico,PUR,Puerto Rico,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
138162,141555,Andy Anderson,1996-04-13,Vancouver,British Columbia,CAN,Canada,NaN,NaN,NaN
138616,142027,Andy Díaz,1995-12-25,NaN,NaN,NaN,Cuba,NaN,NaN,NaN
138620,142031,Andy Cruz,1995-08-12,NaN,NaN,NaN,Cuba,NaN,NaN,NaN
138623,142034,Andy Granda,1992-02-04,Matanzas,Matanzas,CUB,Cuba,NaN,NaN,NaN
145415,149138,Andy Miele,1988-04-15,Grosse Pointe Woods,Michigan,USA,United States,NaN,NaN,NaN

In [257]:
# here the index has been set to 'name' column. 
# customer.set_index('name', inplace=True), the "name" column was moved out of the standard DataFrame columns and became the row index.
# customer.loc[customer['name'].str.startswith('Andy')] -> this usual syntax won't work cause no 'name' column exists now
import pandas as pd
customer = pd.read_csv('../data/external/bios.csv')
customer.set_index('name', inplace=True)
customer.loc[customer.index.str.contains('Andy', na=False)]

,athlete_id,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
name,,,,,,,,,
Andy Goode,96,1960-01-30,Welwyn Garden City,England,GBR,Great Britain,183.0,83.0,NaN
Andy Straughn,3502,1961-05-11,NaN,NaN,NaN,Great Britain,190.0,81.0,NaN
Andy Campbell,5819,1956-07-21,Melbourne,Victoria,AUS,Australia,218.0,93.0,NaN
Andy dela Cruz,5968,1923-11-10,Pasay City,Manila,PHI,Philippines,NaN,NaN,1993-06-05
Andy Agosto,7811,1970-09-11,Carolina,Puerto Rico,PUR,Puerto Rico,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
Andy Anderson,141555,1996-04-13,Vancouver,British Columbia,CAN,Canada,NaN,NaN,NaN
Andy Díaz,142027,1995-12-25,NaN,NaN,NaN,Cuba,NaN,NaN,NaN
Andy Cruz,142031,1995-08-12,NaN,NaN,NaN,Cuba,NaN,NaN,NaN
Andy Granda,142034,1992-02-04,Matanzas,Matanzas,CUB,Cuba,NaN,NaN,NaN
Andy Miele,149138,1988-04-15,Grosse Pointe Woods,Michigan,USA,United States,NaN,NaN,NaN

In [258]:
# to count the number of occurrences of each unique value in the 'FIRST_NAME' column and display the top 10 most common first names in descending order by default
employees = pd.read_csv('../data/external/employees.csv')
employees.FIRST_NAME.value_counts().head(10)

FIRST_NAME
Michael      2
Steven       2
Alexander    2
John         2
James        2
Donald       1
Douglas      1
Jennifer     1
Pat          1
Susan        1
Name: count, dtype: int64

In [259]:
# to count the number of occurrences of each unique value in the 'weight_kg' column and display the top 5 most common weights
import pandas as pd
customer = pd.read_csv('../data/external/bios.csv')
filtered = customer.weight_kg.value_counts(ascending=False)
filtered.head(10)

weight_kg
70.0    4688
75.0    4120
60.0    3728
68.0    3545
80.0    3290
65.0    3275
72.0    3110
73.0    3013
63.0    2735
64.0    2600
Name: count, dtype: int64

In [260]:
# to display occurance of only one particular weight from above
print(filtered[70.0])

4688

### Sorting Columns

In [261]:
# to sort the dataframe by FIRST_NAME in ascending order. Since 'inplace=True', we can directly call 'employees.head()' to see final result as changes from sort have taken place permanentely.
employees.sort_values('FIRST_NAME', inplace=True)
employees.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
30,121,Adam,Fripp,AFRIPP,650.123.2234,10-APR-05,ST_MAN,8200,-,100,50
12,103,Alexander,Hunold,AHUNOLD,590.423.4567,03-JAN-06,IT_PROG,9000,-,102,60
24,115,Alexander,Khoo,AKHOO,515.127.4562,18-MAY-03,PU_CLERK,3100,-,114,30
13,104,Bruce,Ernst,BERNST,590.423.4568,21-MAY-07,IT_PROG,6000,-,103,60
18,109,Daniel,Faviet,DFAVIET,515.124.4169,16-AUG-02,FI_ACCOUNT,9000,-,108,100

In [262]:
# to sort the dataframe by SALARY in descending order and then by FIRST_NAME in ascending order. 
# When two or more rows have the same value in the SALARY column, they will be sorted by FIRST_NAME in ascending order.
employees.sort_values(['SALARY', 'FIRST_NAME'], ascending=[False, True], inplace=True)
employees.loc[employees.SALARY == 9000]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
12,103,Alexander,Hunold,AHUNOLD,590.423.4567,03-JAN-06,IT_PROG,9000,-,102,60
18,109,Daniel,Faviet,DFAVIET,515.124.4169,16-AUG-02,FI_ACCOUNT,9000,-,108,100

In [263]:
# not using inplace=True to keep original dataframe as it is and instead store chnages in new DF
employees = pd.read_csv('../data/external/employees.csv')
sorted_df = employees.sort_values(['SALARY', 'EMPLOYEE_ID'], ascending=[False, True])
sorted_df.loc[sorted_df['SALARY'] == 17000]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
10,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21-SEP-05,AD_VP,17000,-,100,90
11,102,Lex,De Haan,LDEHAAN,515.123.4569,13-JAN-01,AD_VP,17000,-,100,90

### Filtering Data

In [264]:
bios = pd.read_csv('../data/external/bios.csv')
bios.tail()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20

In [265]:
# to select rows where height_cm is greater than 210 and born_country is USA, and then select only the name, height_cm and athlete_id columns. 
# Finally, sort the result by height_cm in descending order.
result = bios.loc[(bios['height_cm'] > 210) & (bios['born_country'] == 'USA')][['name', 'height_cm', 'athlete_id']]
result = result.sort_values(by='height_cm', ascending=[False])
result.head()

                    name  height_cm  athlete_id
5781      Tommy Burleson      223.0        5804
6937      David Robinson      216.0        6972
6722    Shaquille O'Neal      216.0        6755
123850    Tyson Chandler      216.0      126093
142930        Mike Tobey      213.0      146560

In [266]:
# to select rows where the name column contains either 'Michael' or 'Rahul', ignoring case, and then sort the result by name in ascending order.
filter = bios.loc[bios['name'].str.contains('Michael|Rahul')]
filter = filter.sort_values(by='name', ascending=True)
filter.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
23953,24140,Michael Jackson,1963-11-19,Valença,Rio de Janeiro,BRA,Brazil,168.0,63.0,NaN
8686,8733,Bill Michaels,1876-07-13,Alcoa,Tennessee,USA,United States,NaN,NaN,1934-01-01
81946,82598,Carl Michaels,1981-05-21,Cape Town,Western Cape,RSA,South Africa,186.0,81.0,NaN
42284,42607,Christoph-Michael Zeisner,1943-12-05,Gütersloh,Nordrhein-Westfalen,GER,West Germany,182.0,71.0,2022-07-12
20272,20416,David McMichael,1961-04-22,Philadelphia,Pennsylvania,USA,United States,172.0,68.0,NaN

In [267]:
# to select rows where the born_country column is either 'USA' or 'GBR', and the name column starts with 'Bill'.
bios.loc[(bios['born_country'].isin(['USA','GBR'])) & (bios['name'].str.startswith('Bill'))]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
3226,3238,Billy Koch,1974-12-14,Rockville Centre,New York,USA,United States,190.0,100.0,NaN
3361,3373,Bill Child,1884-08-07,Swaffham,England,GBR,Great Britain,NaN,NaN,1961-01-01
3372,3384,Bill Dees,1874-09-28,Liverpool,England,GBR,Great Britain,NaN,NaN,1940-10-18
3514,3526,Billy Wells,1936-09-07,London,England,GBR,Great Britain,190.0,84.0,2008-01-01
3925,3939,Billy Barnes,1924-01-01,Belfast,Northern Ireland,GBR,Ireland,NaN,NaN,2006-08-31
...,...,...,...,...,...,...,...,...,...,...
111673,112917,Billy Joe Saunders,1989-08-30,Hatfield,England,GBR,Great Britain,180.0,69.0,NaN
113393,114684,Billy Nelson,1984-09-11,Bakersfield,California,USA,United States,165.0,55.0,NaN
121254,123228,Bill Lucas,1987-09-13,Exeter,England,GBR,Great Britain,199.0,100.0,NaN
125451,127796,Billy Morgan,1989-04-02,Southampton,England,GBR,Great Britain,181.0,72.0,NaN
144650,148346,Billy Major,1996-11-21,Cambridge,England,GBR,Great Britain,NaN,NaN,NaN

In [268]:
# to select rows where the born_country column is either 'USA' or 'GBR', and the name column starts with 'Bill' using query method.
filter = bios.query('born_country in ["USA", "GBR"] and name.str.startswith("Bill")')
filter.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
3226,3238,Billy Koch,1974-12-14,Rockville Centre,New York,USA,United States,190.0,100.0,NaN
3361,3373,Bill Child,1884-08-07,Swaffham,England,GBR,Great Britain,NaN,NaN,1961-01-01
3372,3384,Bill Dees,1874-09-28,Liverpool,England,GBR,Great Britain,NaN,NaN,1940-10-18
3514,3526,Billy Wells,1936-09-07,London,England,GBR,Great Britain,190.0,84.0,2008-01-01
3925,3939,Billy Barnes,1924-01-01,Belfast,Northern Ireland,GBR,Ireland,NaN,NaN,2006-08-31

### Adding/Removing Columns

In [269]:
people = pd.read_csv('../data/external/some-people.csv')
people.head()

      name  age born_country
0    Alice   30          USA
1      Bob   25          GBR
2  Charlie   35          CAN
3    David   28          USA
4      Eve   22          GBR

In [270]:
# to add a new column 'year' to the dataframe and set its value to 1985 for all rows.
people['year'] = 1985
people.head()

      name  age born_country  year
0    Alice   30          USA  1985
1      Bob   25          GBR  1985
2  Charlie   35          CAN  1985
3    David   28          USA  1985
4      Eve   22          GBR  1985

In [271]:
# modify value of existing record, if key doesn't exist then create a entry with the same
people.loc[1, 'name'] = 'Akshay' # changes name to 'Akshay'
people.loc[2000, 'name'] = 'John' # creates new entry at index 2000
people.head(100)

         name   age born_country    year
0       Alice  30.0          USA  1985.0
1      Akshay  25.0          GBR  1985.0
2     Charlie  35.0          CAN  1985.0
3       David  28.0          USA  1985.0
4         Eve  22.0          GBR  1985.0
5       Frank  40.0          CAN  1985.0
6       Grace  27.0          USA  1985.0
7       Heidi  32.0          GBR  1985.0
8        Ivan  29.0          CAN  1985.0
9        Judy  31.0          USA  1985.0
2000     John   NaN          NaN     NaN

In [272]:
# to create new column 'actual_year' with values: 2000 if born_country == 'USA' otherwise 2010
import numpy as np
people['actual_year'] = np.where(people['born_country'] == 'USA', 2000, 2010)  # np.where(condition, value_if_true, value_if_false)
people.head()

      name   age born_country    year  actual_year
0    Alice  30.0          USA  1985.0         2000
1   Akshay  25.0          GBR  1985.0         2010
2  Charlie  35.0          CAN  1985.0         2010
3    David  28.0          USA  1985.0         2000
4      Eve  22.0          GBR  1985.0         2010

In [273]:
# to drop the 'year' column from the dataframe. This will return a new dataframe without the 'year' column, but it will not modify the original dataframe unless we set inplace=True.
people.drop(columns=['year'])
people.head(4)

      name   age born_country    year  actual_year
0    Alice  30.0          USA  1985.0         2000
1   Akshay  25.0          GBR  1985.0         2010
2  Charlie  35.0          CAN  1985.0         2010
3    David  28.0          USA  1985.0         2000

In [274]:
# to drop 'year' column from actual dataframe
people.drop(columns=['year'], inplace=True)
people.head(2)

     name   age born_country  actual_year
0   Alice  30.0          USA         2000
1  Akshay  25.0          GBR         2010

In [275]:
# to add a new column 'age_after_5years' to the dataframe, which is the age of the person after 5 years. This is done by adding 5 to the 'age' column.
people['age_after_5years'] = people['age'] + 5
people.head(2)

     name   age born_country  actual_year  age_after_5years
0   Alice  30.0          USA         2000              35.0
1  Akshay  25.0          GBR         2010              30.0

In [276]:
# to rename the column 'age_after_5years' to 'age_in_5_years'. This will modify the original dataframe because we set inplace=True.
people.rename(columns={'age_after_5years': 'age_in_5_years'}, inplace=True)
people.head(2)

     name   age born_country  actual_year  age_in_5_years
0   Alice  30.0          USA         2000            35.0
1  Akshay  25.0          GBR         2010            30.0

In [277]:
# to select rows where the first name is 'Albert'. We will first create a new column 'first_name' by splitting the 'name' column and taking the first part of the name. 
# Then we will filter the rows where 'first_name' is 'Albert'.
bios_new = bios.copy()
bios_new['first_name'] = bios_new['name'].str.split().str[0]
bios_new.loc[bios_new['first_name'] == 'Albert']

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert
28,29,Albert Lippmann,NaN,NaN,NaN,NaN,France,NaN,NaN,NaN,Albert
461,462,Albert Dauchez,NaN,NaN,NaN,NaN,France,NaN,NaN,NaN,Albert
480,481,Albert le Tyrant,1946-09-12,NaN,NaN,NaN,France,170.0,70.0,NaN,Albert
678,681,Albert Lammens,1890-06-17,Bruxelles (Brussels),Région de Bruxelles-Capitale,BEL,Belgium,NaN,NaN,1933-10-07,Albert
...,...,...,...,...,...,...,...,...,...,...,...
138515,141924,Albert Mengue,1999-04-18,NaN,NaN,NaN,Cameroon,NaN,NaN,NaN,Albert
139097,142547,Albert Beltrán,1993-10-23,Sabadell,Barcelona,ESP,Spain,179.0,73.0,NaN,Albert
142610,146223,Albert Batyrgaziyev,1998-06-23,Babayurt,Respublika Dagestan,RUS,ROC,NaN,NaN,NaN,Albert
143350,146994,Albert Chemutai,1999-11-25,NaN,NaN,NaN,Uganda,NaN,NaN,NaN,Albert
144702,148402,Albert Kuchler,1998-11-30,Bad Kötzting,Bayern,GER,Germany,NaN,NaN,NaN,Albert

In [278]:
# to create a new column 'born_datetime' by converting the 'born_date' column to a datetime object. 
# Then we will extract the year from the 'born_datetime' column and store it in a new column 'born_year'.
bios_new['born_datetime'] = pd.to_datetime(bios_new['born_date'], format='%Y-%m-%d')
bios_new['born_year'] = bios_new['born_datetime'].dt.year
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime,born_year
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01,1969.0
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13,1898.0
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895.0
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17,1878.0

#### Save dataframe to new csv file

In [279]:
# to save the modified dataframe to a new CSV file called 'bios_new.csv' in the 'processed' folder. 
# We will set index=False to avoid saving the index as a separate column in the CSV file.
bios_new.to_csv('../data/processed/bios_new.csv', index=False)

In [280]:
# to create a new column 'height_category' based on the values in the 'height_cm' column.
bios_new['height_category'] = bios_new['height_cm'].apply(
    lambda x: 'Short' if x<165 else 'Average' if x<185 else 'Tall'
    )
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime,born_year,height_category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0,Tall
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01,1969.0,Average
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13,1898.0,Average
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895.0,Average
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17,1878.0,Tall

In [281]:
# to create 'height_category' using numpy.select() (recommended for multiple conditions)
import numpy as np

conditions = [
    bios_new['height_cm'] < 165,
    bios_new['height_cm'] < 185
]

choices = ['Short', 'Average']

bios_new['height_category'] = np.select(
    conditions,
    choices,
    default='Tall'
)
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime,born_year,height_category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0,Tall
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01,1969.0,Average
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13,1898.0,Average
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895.0,Average
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17,1878.0,Tall

In [282]:
# to create a new column 'weight_category' based on the values in the 'weight_kg' column. 
# We will use the apply method to apply a function that categorizes the weight into 'Lightweight', 'Middleweight' and 'Heavyweight'. 
# axis=1 is used to apply the function to each row of the dataframe. 
def categorize_weight(row):
    if row['height_cm'] < 165 and row['weight_kg'] < 70:
        return 'Lightweight'
    elif row['height_cm'] < 185 and row['weight_kg'] < 85:
        return 'Middleweight'
    else:
        return 'Heavyweight'
    
bios_new['weight_category'] = bios_new.apply(categorize_weight, axis=1)
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime,born_year,height_category,weight_category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0,Tall,Heavyweight
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01,1969.0,Average,Middleweight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13,1898.0,Average,Middleweight
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895.0,Average,Middleweight
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17,1878.0,Tall,Heavyweight

### Merging and Concatenating Data

In [283]:
nocs = pd.read_csv('../data/external/noc_regions.csv')
bios = pd.read_csv('../data/external/bios.csv')

In [284]:
# to merge the bios and nocs dataframes on the born_country and NOC columns respectively. 
# We will use a left join to keep all the rows from the bios dataframe and add the corresponding region information from the nocs dataframe.
# how='left' mean Keep all rows from bios, even if no match is found in nocs
bios_new = pd.merge(bios, nocs, left_on='born_country', right_on='NOC', how='left')
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,NOC_y,region,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,FRA,France,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,FRA,France,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,FRA,France,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,FRA,France,NaN
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,GBR,UK,NaN

In [285]:
# for identifying invalid country codes in bios_new
bios_nan = bios_new[bios_new['NOC_x'].isna()]
bios_nan.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,NOC_y,region,notes
137270,140621,Jocelyn Bartram,1993-05-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [286]:
# to select rows where the NOC_x column (which is the born_country from bios) is not equal to the region column (which is the region from nocs).
# One practical note: if either NOC_x or region contains NaN, then != treats NaN != NaN as True. 
# That means rows with missing values may appear in your result unless you handle missing data explicitly.
bios_new.loc[bios_new['NOC_x'] != bios_new['region']][['name', 'born_country', 'NOC_x', 'region']]

                       name born_country    NOC_x   region
4              Albert Canet          GBR   France       UK
12                J. Defert          NaN   France      NaN
13           Étienne Durand          NaN   France      NaN
16               Guy Forget          MAR   France  Morocco
27       Guy, Baron Lejeune          NaN   France      NaN
...                     ...          ...      ...      ...
145491        Matthew Wepke          NaN  Jamaica      NaN
145493   Landysh Falyakhova          RUS      ROC   Russia
145495    Polina Luchnikova          RUS      ROC   Russia
145496  Valeriya Merkusheva          RUS      ROC   Russia
145497      Yuliya Smirnova          RUS      ROC   Russia

[73210 rows x 4 columns]

In [287]:
# to select rows where the born_country column is either 'USA' or 'GBR', 
# and then concatenate the resulting dataframes for USA and GBR into a new dataframe called new_df. Concat puts one DF on top of another DF.
usa = bios_new.loc[bios_new['born_country'] == 'USA']
gbr = bios_new.loc[bios_new['born_country'] == 'GBR']

new_df = pd.concat([usa, gbr], ignore_index=True)

In [288]:
# to display the first 2 rows of the new_df dataframe with USA and GBR athletes.
new_df.head(2)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,NOC_y,region,notes
0,55,Monique Javer,1967-07-22,Burlingame,California,USA,Great Britain,177.0,64.0,NaN,USA,USA,NaN
1,964,Xóchitl Escobedo,1968-09-17,West Covina,California,USA,Mexico,170.0,60.0,NaN,USA,USA,NaN

In [289]:
# to display the last 2 rows of the new_df dataframe with USA and GBR athletes.
new_df.tail(2)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,NOC_y,region,notes
15431,149041,Axel Brown,1992-04-02,Harrogate,England,GBR,Trinidad and Tobago,NaN,NaN,NaN,GBR,UK,NaN
15432,149111,Jean-Luc Baker,1993-10-07,Burnley,England,GBR,United States,NaN,NaN,NaN,GBR,UK,NaN

In [290]:
# Merging two DF on common ID
result = pd.read_csv('../data/external/results.csv')
combined_df = pd.merge(result, new_df, on='athlete_id', how='left')
combined_df.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,...,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,NOC_y,region,notes
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Handling Null Values

In [291]:
# modify existing DF to insert some null values and then handle them
people = pd.read_csv('../data/external/some-people.csv')
people.head()

      name  age born_country
0    Alice   30          USA
1      Bob   25          GBR
2  Charlie   35          CAN
3    David   28          USA
4      Eve   22          GBR

In [292]:
# inserting null values to row 1,2 and column 'age'
people.loc[1:2, 'age'] = np.nan
people.head(5)

      name   age born_country
0    Alice  30.0          USA
1      Bob   NaN          GBR
2  Charlie   NaN          CAN
3    David  28.0          USA
4      Eve  22.0          GBR

In [293]:
# to get sum of null values in each column
people.isna().sum()

name            0
age             2
born_country    0
dtype: int64

In [294]:
# to fill null values in 'age' column with the mean of the 'age' column. This will modify the original dataframe.
people = people.fillna(people['age'].mean())
people.head()

      name     age born_country
0    Alice  30.000          USA
1      Bob  29.875          GBR
2  Charlie  29.875          CAN
3    David  28.000          USA
4      Eve  22.000          GBR

In [295]:
# to fill null values with linear interpolation method. This will modify the original dataframe.
people.loc[3:4, 'age'] = np.nan # first we are inserting null values to row 3 and 4 and column 'age' to demonstrate interpolation method
people['age'] = people['age'].interpolate() # interpolation method fills the null values by calculating the average of the previous and next non-null values in the 'age' column.
people.head(6)

      name     age born_country
0    Alice  30.000          USA
1      Bob  29.875          GBR
2  Charlie  29.875          CAN
3    David  33.250          USA
4      Eve  36.625          GBR
5    Frank  40.000          CAN

In [296]:
# dropna() method is used to remove rows with null values in the 'age' column. 
# subset parameter specifies the column to check for null values. inplace=True modifies the original dataframe.
people.loc[1:2, 'age'] = np.nan
people.dropna(subset=['age'], inplace=True)
people.head(5)

    name     age born_country
0  Alice  30.000          USA
3  David  33.250          USA
4    Eve  36.625          GBR
5  Frank  40.000          CAN
6  Grace  27.000          USA

In [297]:
# to select rows where the 'age' column has null values. This will return a new dataframe with only the rows where 'age' is null.
people = pd.read_csv('../data/external/some-people.csv')
people.loc[1:2, 'age'] = np.nan
people.loc[people['age'].isna()]

      name  age born_country
1      Bob  NaN          GBR
2  Charlie  NaN          CAN

In [298]:
# to select rows where the 'age' column does not have null values. This will return a new dataframe with only the rows where 'age' is not null.
people.loc[people['age'].notna()]

    name   age born_country
0  Alice  30.0          USA
3  David  28.0          USA
4    Eve  22.0          GBR
5  Frank  40.0          CAN
6  Grace  27.0          USA
7  Heidi  32.0          GBR
8   Ivan  29.0          CAN
9   Judy  31.0          USA

### Aggregating Values

In [299]:
# to count the number of occurrences of each unique value in the 'born_city' column and display the top 10 most common cities in descending order by default
bios['born_city'].value_counts()

born_city
Budapest            1378
Moskva (Moscow)      883
Oslo                 708
Stockholm            629
Praha (Prague)       600
                    ...
Tsivilsk               1
Roth                   1
Romoos                 1
Dva Polya Artash       1
Dulwich Hill           1
Name: count, Length: 22368, dtype: int64

In [300]:
# Here, we are first filtering the rows where born_country is 'USA' and then applying value_counts() on the 'born_city' column to get the count of each unique city. 
# Finally, we are using head(5) to display the top 5 most common cities.
bios.loc[bios['born_country'] == 'USA'][['born_city']].value_counts().head(5)

born_city
New York        416
Chicago         283
Los Angeles     230
Philadelphia    205
Boston          153
Name: count, dtype: int64

In [301]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [302]:
# to calculate the average height in centimeters for each unique value in the 'NOC' column. 
# This will return a new Series with the NOC as the index and the average height as the values.
bios.groupby(['NOC'])['height_cm'].mean()

NOC
Afghanistan               170.170732
Albania                   174.200000
Albania Australia         166.000000
Albania Bulgaria          189.000000
Albania Greece            165.000000
                             ...
West Indies Federation    176.000000
Yemen                     169.391304
Yugoslavia                180.035980
Zambia                    169.852174
Zimbabwe                  173.335196
Name: height_cm, Length: 696, dtype: float64

In [303]:
# `agg()` method allows us to perform multiple aggregation operations on different columns of the grouped data.
# `agg()` method takes a dictionary where the keys are the column names and the values are the aggregation functions to be applied to those columns.
# Here, we are grouping the data by both 'NOC' and 'born_city' columns, and then applying the mean aggregation function to both 'height_cm' and 'weight_kg' columns.
# Note: Since there are some null values in 'height_cm' and 'weight_kg' columns, 
# we are using interpolate() method to fill those null values before applying the groupby and agg operations.
bios['height_cm'] = bios['height_cm'].interpolate()
bios['weight_kg'] = bios['weight_kg'].interpolate()
bios.groupby(['NOC', 'born_city']).agg({'height_cm': 'mean', 'weight_kg': 'mean'}).head()

                        height_cm   weight_kg
NOC         born_city
Afghanistan Kabul      170.363636   68.431818
            Kandahar   165.000000   55.000000
Albania     Dibër      159.000000   45.000000
            Durrës     180.000000  100.000000
            Elbasan    173.500000   77.250000

In [304]:
coffee = pd.read_csv('../data/external/coffee.csv')
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [305]:
# to create a pivot table that shows the total units sold for each coffee type on each day.
# The pivot() method is used to reshape the data in the coffee dataframe.
# The columns parameter specifies the column to use as the new columns in the pivot table,
# the index parameter specifies the column to use as the new index in the pivot table, and
# the values parameter specifies the column to use for populating the values in the pivot table.
# After creating the pivot table, we are reindexing it to ensure that the days of the week are in the correct order.
pivot = coffee.pivot(
    columns='Coffee Type', 
    index='Day', 
    values='Units Sold'
    )
pivot = pivot.reindex([
    'Monday',
    'Tuesday',
    'Wednesday',
    'Thursday',
    'Friday',
    'Saturday',
    'Sunday'
])
pivot

Coffee Type  Espresso  Latte
Day
Monday             25     15
Tuesday            30     20
Wednesday          35     25
Thursday           40     30
Friday             45     35
Saturday           45     35
Sunday             45     35

In [306]:
# to access the total units sold for 'Latte' on 'Monday' from the pivot table. This will return a single value which is the total units sold for 'Latte' on 'Monday'.
x = pivot.loc['Monday','Latte'] #np.int64(15)
int(x)

15

In [307]:
# to calculate the total units sold for each coffee type across all days. This will return a Series with the coffee types as the index and the total units sold as the values.
pivot.sum()

Coffee Type
Espresso    265
Latte       195
dtype: int64

In [308]:
# to calculate the total units sold for each day across all coffee types. This will return a Series with the days of the week as the index and the total units sold as the values.
pivot.sum(axis=1)

Day
Monday       40
Tuesday      50
Wednesday    60
Thursday     70
Friday       80
Saturday     80
Sunday       80
dtype: int64

In [309]:
# to convert the 'born_date' column to a datetime object and then group the data by the year of birth and count the number of athletes born in each year. 
# Finally, we are sorting the result by the count of athletes in descending order.
# `reset_index()` is used to convert the Series returned by groupby into a DataFrame, and `sort_values()` is used to sort the DataFrame by the 'athlete_id' column in descending order.
bios['born_date'] = pd.to_datetime(bios['born_date'])
bios.groupby(bios['born_date'].dt.year)['athlete_id'].count().reset_index().sort_values('athlete_id', ascending=False)

     born_date  athlete_id
139     1972.0        2231
152     1985.0        2227
140     1973.0        2216
138     1971.0        2205
137     1970.0        2174
..         ...         ...
5       1838.0           1
4       1837.0           1
3       1836.0           1
2       1833.0           1
176     2009.0           1

[177 rows x 2 columns]

In [310]:
# to create a new column 'latte_revenue_by_day' that contains the total revenue for 'Latte' on each day.
# We are filtering the coffee dataframe to include only rows where the 'Coffee Type' is 'Latte', then grouping the data by 'Day' and summing the 'Revenue' for each day.
# After calculating the total revenue for 'Latte' on each day, we are finding the day with the highest revenue and the corresponding revenue amount.
# `idxmax()` is used to get the index of the maximum value in the Series, which in this case will be the day with the highest revenue for 'Latte'.
# `max()` is used to get the maximum value in the Series, which in this case will be the highest revenue for 'Latte'.
latte_revenue_by_day = coffee.loc[coffee['Coffee Type'] == 'Latte'].groupby('Day')['Revenue'].sum()
best_day = latte_revenue_by_day.idxmax()
best_revenue = latte_revenue_by_day.max()

latte_revenue_by_day, best_day, best_revenue

KeyError: 'Column not found: Revenue'

### Advanced Functionality

In [ ]:
# to create a new column 'Price' in the coffee dataframe by mapping the 'Coffee Type' column to a price using a dictionary.
# The map() method is used to map the values in the 'Coffee Type' column to the corresponding prices in the price_map dictionary.
# We are creating a price_map dictionary where the keys are the coffee types and the values are their corresponding prices.
# After creating the 'Price' column, we are calculating the 'Revenue' by multiplying the 'Units Sold' column with the 'Price' column.
price_map = {
    'Espresso': 3.99,
    'Latte': 5.99
}

coffee['Price'] = coffee['Coffee Type'].map(price_map)
coffee['Revenue'] = coffee['Units Sold'] * coffee['Price']
coffee.head()

         Day Coffee Type  Units Sold  price  Price  Revenue
0     Monday    Espresso          25   3.99   3.99    99.75
1     Monday       Latte          15   5.99   5.99    89.85
2    Tuesday    Espresso          30   3.99   3.99   119.70
3    Tuesday       Latte          20   5.99   5.99   119.80
4  Wednesday    Espresso          35   3.99   3.99   139.65

In [ ]:
# to create a new column 'yesterday_revenue' that contains the revenue from two days ago.
# The shift() method is used to shift the values in the 'Revenue' column down by 2 rows, 
# which means that the value in the 'yesterday_revenue' column for a given row will be the value from the 'Revenue' column that is 2 rows above it.
# shift(2) is done cause there are two types of coffee and we want to get the revenue from the same coffee type from two days ago.
coffee['yesterday_revenue'] = coffee['Revenue'].shift(2)
coffee.head(8)

         Day Coffee Type  Units Sold  price  Price  Revenue  yesterday_revenue
0     Monday    Espresso          25   3.99   3.99    99.75                NaN
1     Monday       Latte          15   5.99   5.99    89.85                NaN
2    Tuesday    Espresso          30   3.99   3.99   119.70              99.75
3    Tuesday       Latte          20   5.99   5.99   119.80              89.85
4  Wednesday    Espresso          35   3.99   3.99   139.65             119.70
5  Wednesday       Latte          25   5.99   5.99   149.75             119.80
6   Thursday    Espresso          40   3.99   3.99   159.60             139.65
7   Thursday       Latte          30   5.99   5.99   179.70             149.75

In [ ]:
# to calculate the percentage change in revenue compared to two days ago and store it in a new column 'pct_change'.
# We are calculating the percentage change in revenue by dividing the current revenue by the yesterday's revenue, 
# subtracting 1 from the result to get the change, and then multiplying by 100 to convert it to a percentage.
coffee['pct_change'] = (coffee['Revenue'] / coffee['yesterday_revenue'] - 1) * 100
coffee.head(8)

,Day,Coffee Type,Units Sold,price,Price,Revenue,yesterday_revenue,pct_change
0,Monday,Espresso,25,3.99,3.99,99.75,NaN,NaN
1,Monday,Latte,15,5.99,5.99,89.85,NaN,NaN
2,Tuesday,Espresso,30,3.99,3.99,119.70,99.75,20.000000
3,Tuesday,Latte,20,5.99,5.99,119.80,89.85,33.333333
4,Wednesday,Espresso,35,3.99,3.99,139.65,119.70,16.666667
5,Wednesday,Latte,25,5.99,5.99,149.75,119.80,25.000000
6,Thursday,Espresso,40,3.99,3.99,159.60,139.65,14.285714
7,Thursday,Latte,30,5.99,5.99,179.70,149.75,20.000000

In [ ]:
# to rank the athletes based on their height in centimeters and create a new column 'height_rank' that contains the rank of each athlete.
# The rank() method is used to assign a rank to each value in the 'height_cm
# The two athletes with height 223 occupy positions 2 and 3. Their rank is: (2 + 3) / 2 = 2.5
bios['height_rank'] = bios['height_cm'].rank(ascending=False)
bios.sort_values(['height_rank'])[['name', 'height_cm', 'height_rank']].head(10)

                      name  height_cm  height_rank
89070             Yao Ming      226.0          1.0
5781        Tommy Burleson      223.0          2.5
6978       Arvydas Sabonis      223.0          2.5
89075       Roberto Dueñas      221.0          5.0
120266        Zhang Zhaoxu      221.0          5.0
5673        Gunther Behnke      221.0          5.0
7188    Vladimir Tkachenko      220.0          8.0
6504           Luc Longley      220.0          8.0
5089    Viktor Pankrashkin      220.0          8.0
118676     Dmitry Musersky      219.0         10.5

In [ ]:
# to calculate the cumulative sum of the 'Revenue' column and store it in a new column 'Cumulative_Revenue'.
# The cumsum() method is used to calculate the cumulative sum of the 'Revenue' column, which means that each value in the 'Cumulative_Revenue' 
# column will be the sum of all the previous values in the 'Revenue' column up to that point.
coffee['Cumulative_Revenue'] = coffee['Revenue'].cumsum()
coffee.head()

,Day,Coffee Type,Units Sold,price,Price,Revenue,yesterday_revenue,pct_change,Cumalative_Revenue
0,Monday,Espresso,25,3.99,3.99,99.75,NaN,NaN,99.75
1,Monday,Latte,15,5.99,5.99,89.85,NaN,NaN,189.60
2,Tuesday,Espresso,30,3.99,3.99,119.70,99.75,20.000000,309.30
3,Tuesday,Latte,20,5.99,5.99,119.80,89.85,33.333333,429.10
4,Wednesday,Espresso,35,3.99,3.99,139.65,119.70,16.666667,568.75

In [ ]:
latte = coffee.loc[coffee['Coffee Type'] == 'Latte'].copy()
latte.head()

,Day,Coffee Type,Units Sold,price,Price,Revenue,yesterday_revenue,pct_change,Cumalative_Revenue
1,Monday,Latte,15,5.99,5.99,89.85,NaN,NaN,189.6
3,Tuesday,Latte,20,5.99,5.99,119.80,89.85,33.333333,429.1
5,Wednesday,Latte,25,5.99,5.99,149.75,119.80,25.000000,718.5
7,Thursday,Latte,30,5.99,5.99,179.70,149.75,20.000000,1057.8
9,Friday,Latte,35,5.99,5.99,209.65,179.70,16.666667,1447.0

In [ ]:
# to calculate the rolling sum of the 'Units Sold' column for a window of 3 days and store it in a new column '3_day_cumulative_units'.
# The rolling() method is used to calculate the rolling sum of the 'Units Sold' column for a window of 3 days, 
# which means that each value in the '3_day_cumulative_units' column will be the sum of the current and previous 2 values in the 'Units Sold' column.
latte['3_day_cumulative_units'] = latte['Units Sold'].rolling(3).sum()
latte

,Day,Coffee Type,Units Sold,price,Price,Revenue,yesterday_revenue,pct_change,Cumalative_Revenue,3_day_cumulative_units
1,Monday,Latte,15,5.99,5.99,89.85,NaN,NaN,189.6,NaN
3,Tuesday,Latte,20,5.99,5.99,119.80,89.85,33.333333,429.1,NaN
5,Wednesday,Latte,25,5.99,5.99,149.75,119.80,25.000000,718.5,60.0
7,Thursday,Latte,30,5.99,5.99,179.70,149.75,20.000000,1057.8,75.0
9,Friday,Latte,35,5.99,5.99,209.65,179.70,16.666667,1447.0,90.0
11,Saturday,Latte,35,5.99,5.99,209.65,209.65,0.000000,1836.2,100.0
13,Sunday,Latte,35,5.99,5.99,209.65,209.65,0.000000,2225.4,105.0